### ISSUE TITLE
Where can i download this plugin?

### ISSUE THREAD

**Issue by adithayyil** [Guyc1800/joplin-latex-autocomplete#1]
the link seems to be dead

![image](https://github.com/Guyc1800/joplin-latex-autocomplete/assets/90326965/6278fcab-2a2f-4ec3-af13-bc9b394569c8)

**Comment by Guyc1800** [comment]
here i just uploaded it 
https://github.com/Guyc1800/joplin-latex-autocomplete/releases/download/cm5/com.latexAutocomplete.jpl
